### ISSUE TITLE
which repo to download from hugging face for 7b / 13b to try out?

### ISSUE THREAD

**Issue by hiqsociety** [mlc-ai/llm-perf-bench#12]
which repo to download from hugging face for 7b / 13b to try out? i did git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-13b-chat-hf-q4f16_1

but it generated a 3.3mb directory. any help on this?

**Comment by junrushao** [comment]
3.3M doesn't look right. Could you double check if you are using "git LFS" already? Run the following command:

```
git lfs install
```

and then clone again
